### ISSUE TITLE
Add py34 compatibility

### ISSUE THREAD

**Issue by davide-ceretti** [davide-ceretti/strategypy#24]

**Comment by raulcd** [comment]
In PR https://github.com/davide-ceretti/strategypy/pull/32 there is compatibility for python3.4 for the base code. ```play.sh``` works as expected. There is not Python3.4 compatibility for the different frontends though. Should we also add this? Should it be done on another PR?

**Comment by davide-ceretti** [comment]
I'd probably add py34 compatibility for https://github.com/davide-ceretti/strategypy/blob/master/strategypy/consolefe.py as well. All the other FEs live in other repos anyway.

**Comment by raulcd** [comment]
Added on PR https://github.com/davide-ceretti/strategypy/pull/32

**Comment by davide-ceretti** [comment]
Closed via https://github.com/davide-ceretti/strategypy/pull/32.

Thanks @raulcd
